# 1. EDA
Bu defterde veri setinin genel yapısı ve temel istatistikleri incelenir.

In [1]:
import sys
sys.path.append('..')
from src.data_prep import load_raw_data, add_features
df = load_raw_data()
df = add_features(df)
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,TARGET,PAY_SUM,LIMIT_PER_PAY,BILL_SUM,AGE_BIN
0,20000,2,2,1,24,2,2,-1,-1,-2,...,689,0,0,0,0,1,689,28.985507,7704,0
1,120000,2,2,2,26,-1,2,0,0,0,...,1000,1000,1000,0,2000,1,5000,23.995201,17077,0
2,90000,2,2,2,34,0,0,0,0,0,...,1500,1000,1000,1000,5000,0,11018,8.167710,101653,1
3,50000,2,2,1,37,0,0,0,0,0,...,2019,1200,1100,1069,1000,0,8388,5.960186,231334,1
4,50000,1,2,1,57,-1,0,-1,0,0,...,36681,10000,9000,689,679,0,59049,0.846740,109339,3

In [2]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.000000,50000.000000,140000.000000,240000.00000,1000000.0
SEX,30000.0,1.603733,0.489129,1.000000,1.000000,2.000000,2.00000,2.0
EDUCATION,30000.0,1.853133,0.790349,0.000000,1.000000,2.000000,2.00000,6.0
MARRIAGE,30000.0,1.551867,0.521970,0.000000,1.000000,2.000000,2.00000,3.0
AGE,30000.0,35.485500,9.217904,21.000000,28.000000,34.000000,41.00000,79.0
PAY_0,30000.0,-0.016700,1.123802,-2.000000,-1.000000,0.000000,0.00000,8.0
PAY_2,30000.0,-0.133767,1.197186,-2.000000,-1.000000,0.000000,0.00000,8.0
PAY_3,30000.0,-0.166200,1.196868,-2.000000,-1.000000,0.000000,0.00000,8.0
PAY_4,30000.0,-0.220667,1.169139,-2.000000,-1.000000,0.000000,0.00000,8.0
PAY_5,30000.0,-0.266200,1.133187,-2.000000,-1.000000,0.000000,0.00000,8.0
PAY_6,30000.0,-0.291100,1.149988,-2.000000,-1.000000,0.000000,0.00000,8.0
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.000000,3558.750000,22381.500000,67091.00000,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.000000,2984.750000,21200.000000,64006.25000,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.000000,2666.250000,20088.500000,60164.75000,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.000000,2326.750000,19052.000000,54506.00000,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.000000,1763.000000,18104.500000,50190.50000,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.000000,1256.000000,17071.000000,49198.25000,961664.0
PAY_AMT1,30000.0,5663.580500,16563.280354,0.000000,1000.000000,2100.000000,5006.00000,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.000000,833.000000,2009.000000,5000.00000,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.000000,390.000000,1800.000000,4505.00000,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.000000,296.000000,1500.000000,4013.25000,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.000000,252.500000,1500.000000,4031.50000,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.000000,117.750000,1500.000000,4000.00000,528666.0
TARGET,30000.0,0.221200,0.415062,0.000000,0.000000,0.000000,0.00000,1.0
PAY_SUM,30000.0,31651.392567,60827.677939,0.000000,6679.750000,14383.000000,33503.50000,3764066.0
LIMIT_PER_PAY,30000.0,8966.498827,47899.314089,0.068651,3.799983,6.381621,14.76618,710000.0
BILL_SUM,30000.0,269861.671200,379564.331162,-336259.000000,28688.000000,126311.000000,342626.50000,5263883.0
AGE_BIN,30000.0,0.993400,0.956619,0.000000,0.000000,1.000000,2.00000,4.0